#!/usr/bin/env python3
"""
AVA GTM — Dashboard Data Updater
Updates src/lib/data.ts with real enrichment stats.

Usage:
    python3 scripts/update_dashboard_data.py
"""

import csv
import json
import re
import time
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CSV_PATH = Path("scripts/leads-enriched-emails.csv")
ENRICHMENT_STATS = Path("scripts/enrichment-stats.json")
UPLOAD_STATS = Path("scripts/upload-stats.json")
DATA_TS_PATH = Path("src/lib/data.ts")


def load_csv_stats() -> dict[str, object]:
    """Load and compute stats from the enriched CSV."""
    if not CSV_PATH.exists():
        return {}

    total = 0
    with_email = 0
    with_phone = 0
    with_website = 0
    by_city: dict[str, int] = defaultdict(int)
    by_verticale: dict[str, int] = defaultdict(int)
    by_verticale_email: dict[str, int] = defaultdict(int)
    scores: list[int] = []

    with open(CSV_PATH, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            total += 1
            if row.get("best_email", "").strip():
                with_email += 1
            if row.get("phone", "").strip():
                with_phone += 1
            if row.get("website", "").strip():
                with_website += 1
            city = row.get("city", "").strip()
            if city:
                by_city[city] += 1
            category = row.get("category", "Non classé")
            by_verticale[category] += 1
            if row.get("best_email", "").strip():
                by_verticale_email[category] += 1
            try:
                scores.append(int(row.get("score", "0")))
            except ValueError:
                pass

    # Top 10 cities
    top_cities = sorted(by_city.items(), key=lambda x: -x[1])[:10]
    # Top 10 verticales
    top_verticales = sorted(by_verticale.items(), key=lambda x: -x[1])[:15]

    return {
        "total": total,
        "with_email": with_email,
        "with_phone": with_phone,
        "with_website": with_website,
        "email_rate": round(with_email / total * 100, 1) if total > 0 else 0,
        "phone_rate": round(with_phone / total * 100, 1) if total > 0 else 0,
        "website_rate": round(with_website / total * 100, 1) if total > 0 else 0,
        "avg_score": round(sum(scores) / len(scores), 1) if scores else 0,
        "top_cities": top_cities,
        "top_verticales": top_verticales,
        "verticale_email_rates": {
            v: round(by_verticale_email.get(v, 0) / c * 100, 1) if c > 0 else 0
            for v, c in top_verticales
        },
    }


def generate_data_ts(stats: dict[str, object]) -> str:
    """Generate the data.ts content with real stats."""
    total = stats.get("total", 8360)
    with_email = stats.get("with_email", 0)
    with_phone = stats.get("with_phone", 0)
    with_website = stats.get("with_website", 0)
    email_rate = stats.get("email_rate", 0)
    phone_rate = stats.get("phone_rate", 0)
    website_rate = stats.get("website_rate", 0)
    avg_score = stats.get("avg_score", 0)
    top_cities = stats.get("top_cities", [])
    top_verticales = stats.get("top_verticales", [])

    # Load upload stats if available
    upload_stats: dict[str, object] = {}
    if UPLOAD_STATS.exists():
        with open(UPLOAD_STATS, "r") as f:
            upload_stats = json.load(f)

    uploaded = upload_stats.get("total_uploaded", 0)
    by_vert_upload = upload_stats.get("by_verticale", {})

    # Pipeline stages
    pipeline_stages = [
        {"name": "Google Maps Scraping", "count": total, "status": "completed"},
        {"name": "Phone Numbers", "count": with_phone, "status": "completed"},
        {"name": "Website Detection", "count": with_website, "status": "completed"},
        {"name": "Email Enrichment", "count": with_email, "status": "completed" if with_email > 0 else "in_progress"},
        {"name": "Instantly Upload", "count": uploaded, "status": "completed" if uploaded > 0 else "pending"},
        {"name": "Campaign Active", "count": 0, "status": "pending"},
    ]

    # Verticale data
    verticale_data = []
    for name, count in (top_verticales if top_verticales else []):
        email_count = stats.get("verticale_email_rates", {}).get(name, 0)
        verticale_data.append({
            "name": name[:30],
            "leads": count,
            "emailRate": email_count,
        })

    # City data
    city_data = []
    for name, count in (top_cities if top_cities else []):
        city_data.append({"name": name, "leads": count})

    now = time.strftime("%Y-%m-%d %H:%M")

    content = f"""// Auto-generated by update_dashboard_data.py — {now}
// DO NOT EDIT MANUALLY — this file is overwritten by the pipeline

export interface Lead {{
  title: string;
  phone: string;
  website: string;
  email: string;
  category: string;
  city: string;
  rating: number;
  reviews: number;
  score: number;
}}

export interface PipelineStage {{
  name: string;
  count: number;
  status: 'completed' | 'in_progress' | 'pending';
}}

export interface VerticaleData {{
  name: string;
  leads: number;
  emailRate: number;
}}

export interface CityData {{
  name: string;
  leads: number;
}}

// ====== STATS (updated by pipeline) ======

export const dashboardStats = {{
  totalLeads: {total},
  withEmail: {with_email},
  withPhone: {with_phone},
  withWebsite: {with_website},
  emailRate: {email_rate},
  phoneRate: {phone_rate},
  websiteRate: {website_rate},
  avgScore: {avg_score},
  uploadedToInstantly: {uploaded},
  lastUpdated: "{now}",
}};

export const pipelineStages: PipelineStage[] = {json.dumps(pipeline_stages, indent=2, ensure_ascii=False)};

export const verticaleData: VerticaleData[] = {json.dumps(verticale_data, indent=2, ensure_ascii=False)};

export const cityData: CityData[] = {json.dumps(city_data, indent=2, ensure_ascii=False)};

// ====== ENRICHMENT SUMMARY ======

export const enrichmentSummary = {{
  method: "Website scraping (aiohttp + BeautifulSoup)",
  cost: "0€",
  pagesScraped: ["/, /contact, /mentions-legales, /a-propos, /about"],
  successRate: {email_rate},
  totalEmailsFound: {with_email},
  totalLeadsProcessed: {total},
  timestamp: "{now}",
}};
"""
    return content


def main() -> None:
    """Main update flow."""
    print("=" * 60)
    print("  AVA GTM — DASHBOARD DATA UPDATER")
    print("=" * 60)

    # Load stats
    print("[Stats] Loading enrichment data...")
    stats = load_csv_stats()

    if not stats:
        print("[WARN] No enrichment CSV found. Using defaults.")
        stats = {"total": 8360, "with_email": 0, "with_phone": 8015, "with_website": 7415}

    print(f"  Total leads:     {stats.get('total', 0)}")
    print(f"  With email:      {stats.get('with_email', 0)} ({stats.get('email_rate', 0)}%)")
    print(f"  With phone:      {stats.get('with_phone', 0)} ({stats.get('phone_rate', 0)}%)")
    print(f"  With website:    {stats.get('with_website', 0)} ({stats.get('website_rate', 0)}%)")

    # Generate data.ts
    print("\n[Generate] Creating src/lib/data.ts...")
    content = generate_data_ts(stats)

    # Write file
    DATA_TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(DATA_TS_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[Done] Written to {DATA_TS_PATH}")
    print("=" * 60)


if __name__ == "__main__":
    main()
